import { sql } from 'drizzle-orm'
import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core'

// =============================================================================
// Better Auth tables (user, session, account, verification)
// These are managed by Better Auth but defined here for type-safe Drizzle queries.
// Schema generated by: npx @better-auth/cli generate (with admin plugin)
// =============================================================================

export const user = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
  image: text('image'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
  // Admin plugin fields
  role: text('role'),
  banned: integer('banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  banExpires: integer('ban_expires', { mode: 'timestamp_ms' }),
  mustChangePassword: integer('must_change_password', { mode: 'boolean' }).default(false),
})

export const authSession = sqliteTable('session', {
  id: text('id').primaryKey(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  impersonatedBy: text('impersonated_by'),
}, (table) => ({
  userIdIdx: index('session_userId_idx').on(table.userId),
}))

export const authAccount = sqliteTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
  refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => ({
  userIdIdx: index('account_userId_idx').on(table.userId),
}))

export const verification = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => ({
  identifierIdx: index('verification_identifier_idx').on(table.identifier),
}))

// =============================================================================
// File-Based Refactor: Only connected accounts remain in DB
// Agents, sessions, messages, and secrets are now file-based
// =============================================================================

// Connected accounts - app-level OAuth connections managed by Composio
export const connectedAccounts = sqliteTable('connected_accounts', {
  id: text('id').primaryKey(),
  composioConnectionId: text('composio_connection_id').notNull().unique(),
  toolkitSlug: text('toolkit_slug').notNull(), // e.g., 'gmail', 'slack', 'github'
  displayName: text('display_name').notNull(), // User-friendly label
  status: text('status', { enum: ['active', 'revoked', 'expired'] })
    .notNull()
    .default('active'),
  userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }), // Owner in auth mode, null in non-auth mode
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  userIdIdx: index('connected_accounts_userId_idx').on(table.userId),
}))

// Agent connected accounts - junction table for agent-to-account mappings
// Note: agentSlug references the agent's directory name, not a DB foreign key
export const agentConnectedAccounts = sqliteTable(
  'agent_connected_accounts',
  {
    id: text('id').primaryKey(),
    agentSlug: text('agent_slug').notNull(), // References agent directory name
    connectedAccountId: text('connected_account_id')
      .notNull()
      .references(() => connectedAccounts.id, { onDelete: 'cascade' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => ({
    agentAccountUnique: uniqueIndex('agent_connected_accounts_unique').on(
      table.agentSlug,
      table.connectedAccountId
    ),
  })
)

// Scheduled tasks - tasks scheduled by agents for future execution
export const scheduledTasks = sqliteTable('scheduled_tasks', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),

  // Schedule configuration
  scheduleType: text('schedule_type', { enum: ['at', 'cron'] }).notNull(),
  scheduleExpression: text('schedule_expression').notNull(),

  // Task details
  prompt: text('prompt').notNull(),
  name: text('name'),

  // Status: pending, executed, cancelled, failed
  status: text('status', { enum: ['pending', 'executed', 'cancelled', 'failed'] })
    .notNull()
    .default('pending'),

  // Timing
  nextExecutionAt: integer('next_execution_at', { mode: 'timestamp_ms' }).notNull(),
  lastExecutedAt: integer('last_executed_at', { mode: 'timestamp_ms' }),

  // Recurrence
  isRecurring: integer('is_recurring', { mode: 'boolean' }).notNull().default(false),
  executionCount: integer('execution_count').notNull().default(0),

  // Session tracking
  lastSessionId: text('last_session_id'),
  createdBySessionId: text('created_by_session_id'),
  createdByUserId: text('created_by_user_id'), // For ACL purposes in auth mode

  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  cancelledAt: integer('cancelled_at', { mode: 'timestamp_ms' }),
})

// Notifications - user notifications for session events
export const notifications = sqliteTable('notifications', {
  id: text('id').primaryKey(),
  type: text('type', { enum: ['session_complete', 'session_waiting', 'session_scheduled'] }).notNull(),
  sessionId: text('session_id').notNull(),
  agentSlug: text('agent_slug').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  isRead: integer('is_read', { mode: 'boolean' }).notNull().default(false),
  userId: text('user_id').references(() => user.id, { onDelete: 'set null' }), // Owner in auth mode, null in non-auth mode
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  readAt: integer('read_at', { mode: 'timestamp_ms' }),
}, (table) => ({
  agentSlugIsReadIdx: index('notifications_agent_slug_is_read_idx').on(table.agentSlug, table.isRead),
  sessionIdIdx: index('notifications_session_id_idx').on(table.sessionId),
  createdAtIdx: index('notifications_created_at_idx').on(table.createdAt),
}))

// Proxy tokens - synthetic tokens for agent-to-proxy authentication
export const proxyTokens = sqliteTable('proxy_tokens', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull().unique(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
})

// Proxy audit log - structured log of all proxied requests
export const proxyAuditLog = sqliteTable('proxy_audit_log', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  accountId: text('account_id').notNull(),
  toolkit: text('toolkit').notNull(),
  targetHost: text('target_host').notNull(),
  targetPath: text('target_path').notNull(),
  method: text('method').notNull(),
  statusCode: integer('status_code'),
  errorMessage: text('error_message'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
})

// Remote MCP servers registered at app level
export const remoteMcpServers = sqliteTable('remote_mcp_servers', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  url: text('url').notNull(),
  userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }), // Owner in auth mode, null in non-auth mode
  authType: text('auth_type', { enum: ['none', 'oauth', 'bearer'] }).notNull().default('none'),

  // Auth tokens
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  tokenExpiresAt: integer('token_expires_at', { mode: 'timestamp_ms' }),

  // OAuth metadata (for token refresh)
  oauthTokenEndpoint: text('oauth_token_endpoint'),
  oauthClientId: text('oauth_client_id'),
  oauthClientSecret: text('oauth_client_secret'),
  oauthResource: text('oauth_resource'),

  // Server metadata (cached from discovery)
  toolsJson: text('tools_json'),
  toolsDiscoveredAt: integer('tools_discovered_at', { mode: 'timestamp_ms' }),

  status: text('status', { enum: ['active', 'error', 'auth_required'] }).notNull().default('active'),
  errorMessage: text('error_message'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

// Junction table: agent → remote MCP mappings
export const agentRemoteMcps = sqliteTable('agent_remote_mcps', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  remoteMcpId: text('remote_mcp_id').notNull()
    .references(() => remoteMcpServers.id, { onDelete: 'cascade' }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  agentMcpUnique: uniqueIndex('agent_remote_mcps_unique').on(table.agentSlug, table.remoteMcpId),
}))

// MCP audit log
export const mcpAuditLog = sqliteTable('mcp_audit_log', {
  id: text('id').primaryKey(),
  agentSlug: text('agent_slug').notNull(),
  remoteMcpId: text('remote_mcp_id').notNull(),
  remoteMcpName: text('remote_mcp_name').notNull(),
  method: text('method').notNull(),
  requestPath: text('request_path').notNull(),
  statusCode: integer('status_code'),
  errorMessage: text('error_message'),
  durationMs: integer('duration_ms'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
})

// Agent ACLs - maps users to agents with roles (auth mode only)
export const agentAcl = sqliteTable('agent_acl', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  agentSlug: text('agent_slug').notNull(),
  role: text('role', { enum: ['owner', 'user', 'viewer'] }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
}, (table) => ({
  userAgentUnique: uniqueIndex('agent_acl_user_agent_unique').on(table.userId, table.agentSlug),
  agentSlugIdx: index('agent_acl_agent_slug_idx').on(table.agentSlug),
}))

// User settings - per-user preferences (uses 'local' sentinel in non-auth mode)
export const userSettings = sqliteTable('user_settings', {
  userId: text('user_id').primaryKey().references(() => user.id, { onDelete: 'cascade' }),
  settings: text('settings').notNull(), // JSON blob validated by Zod
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
})

// Type exports for convenience
export type ConnectedAccount = typeof connectedAccounts.$inferSelect
export type NewConnectedAccount = typeof connectedAccounts.$inferInsert
export type AgentConnectedAccount = typeof agentConnectedAccounts.$inferSelect
export type NewAgentConnectedAccount = typeof agentConnectedAccounts.$inferInsert
export type ScheduledTask = typeof scheduledTasks.$inferSelect
export type NewScheduledTask = typeof scheduledTasks.$inferInsert
export type Notification = typeof notifications.$inferSelect
export type NewNotification = typeof notifications.$inferInsert
export type ProxyToken = typeof proxyTokens.$inferSelect
export type NewProxyToken = typeof proxyTokens.$inferInsert
export type ProxyAuditLogEntry = typeof proxyAuditLog.$inferSelect
export type NewProxyAuditLogEntry = typeof proxyAuditLog.$inferInsert
export type RemoteMcpServer = typeof remoteMcpServers.$inferSelect
export type NewRemoteMcpServer = typeof remoteMcpServers.$inferInsert
export type AgentRemoteMcp = typeof agentRemoteMcps.$inferSelect
export type NewAgentRemoteMcp = typeof agentRemoteMcps.$inferInsert
export type McpAuditLogEntry = typeof mcpAuditLog.$inferSelect
export type NewMcpAuditLogEntry = typeof mcpAuditLog.$inferInsert
export type AgentAcl = typeof agentAcl.$inferSelect
export type NewAgentAcl = typeof agentAcl.$inferInsert
export type UserSettingsRow = typeof userSettings.$inferSelect
export type NewUserSettingsRow = typeof userSettings.$inferInsert
export type User = typeof user.$inferSelect
export type AuthSession = typeof authSession.$inferSelect
export type AuthAccount = typeof authAccount.$inferSelect
export type Verification = typeof verification.$inferSelect
